channels:
- defaults
- conda-forge
- pytorch
dependencies:
- python=3.11
- pytorch
- torchvision
- timm
- scipy
- scikit-learn
- matplotlib
- seaborn
- joblib
- xarray
- pip
- pip:
  - spatialdata
  - conch-open-clip-custom @ git+https://github.com/labsyspharm/conch.git@main#subdirectory=open_clip_custom
name: gutinstinct